- __tests__/e2e/countries.spec.ts
- server/infra/database/CountryRepository.ts
- server/models/Country.ts
- server/routers/countriesRouter.ts
> feat: api leader board

- server/infra/database/BaseRepository.spec.ts
> fix: resolve npm test issue

- .github/workflows/pull-request-ci.yml
> feat: added github actions to run tests for new PR

- server/infra/database/BaseRepository.spec.ts
The following changes have been implemented.
- Turn the query response object into an array object.
Resolves  #22
> Extend the BaseRepository to support: update 

- .eslintrc.js
- .github/workflows/pull-request-ci.yml
- server/infra/database/knex.ts
> workflow runs e2e tests

- server/models/Tree.ts
> feat: add default order by created_at desc

- README.md
> fix typos readme

- server/interfaces/Wallets.ts
> fix and add missing types

- __tests__/e2e/planters.spec.ts
- server/infra/database/PlanterRepository.ts
- server/models/Planter.ts
- server/routers/plantersRouter.ts
> feat: add planter name api endpoint

- deployment/overlays/prod/deployment.yaml
- feat: deploy test
- feat: deploy test
- feat: deploy test
> deploy to prod

- deployment/base/deployment.yaml
- deployment/base/mapping.yaml
- deployment/overlays/development/mapping.yaml
- feat: deploy test
- feat: deploy test
- feat: deploy test
- fix: deploy test
> deploy test

- __tests__/e2e/trees.spec.ts
- server/infra/database/TreeRepository.ts
> feat: endpoint get/tree/id now returns species and country info

- __tests__/e2e/planters.spec.ts
- server/infra/database/PlanterRepository.ts
> feat: endpoint planters/id now return continent and country name

- __tests__/e2e/wallets.spec.ts
- server/infra/database/WalletsRepository.ts
> fix: can send wallet name as a query param to the get walletByIdOrNme endpoint

- __tests__/e2e/tokens.spec.ts
- docs/api/spec/query-api.yaml
- server/infra/database/TokensRepository.ts
- server/models/Tokens.ts
- server/routers/tokensRouter.ts
> feat: get-token-list-by-filter,-support-pagination

- __tests__/e2e/species.spec.ts
- server/infra/database/SpeciesRepository.ts
- server/models/Species.ts
- server/routers/speciesRouter.ts
> feat: added filter by wallet_id for species endpoint

- docs/api/spec/query-api.yaml
- server/app.ts
- server/infra/database/CaptureRepository.ts
- server/infra/database/RawCaptureRepository.ts
- server/interfaces/RawCapture.ts
- server/interfaces/RawCaptureFilter.ts
- server/models/RawCapture.ts
- server/routers/capturesRouter.ts
- server/routers/rawCapturesRouter.ts
- update query.yaml
- add /raw-captures endpoint
- add interface, model, repository for Raw Captures
- includes small edits for /v2/captures endpoint
> Add query for raw-captures (field data for verify tool)

- __tests__/e2e/tokens.spec.ts
- server/infra/database/TokensRepository.ts
for https://github.com/Greenstand/treetracker-web-map-client/issues/593
> feat: extended token endpoint to return basic tree info

- server/infra/database/TreeRepository.ts
- server/models/Tree.ts
> new way to get featured tree

- server/infra/database/OrganizationRepository.ts
- server/infra/database/PlanterRepository.ts
- server/models/Organization.ts
- server/routers/organizationsRouter.ts
> org planter featured

- __tests__/e2e/trees.spec.ts
- server/models/Tree.ts
- server/routers/treesRouter.ts
> feat: implemented Get /trees?planter_id=1&order_by=created_at&desc=true 

- server/infra/database/OrganizationRepository.ts
> feat: add continent to response #141

- __tests__/e2e/countries.spec.ts
- server/infra/database/CountryRepository.ts
- server/routers/countriesRouter.ts
> feat: add filter by continent

- server/infra/database/TreeRepository.ts
Issue #145  API: GET /trees/featured is missing species_name
> feat: added species_name for get featured tree

- __tests__/e2e/species.spec.ts
- server/infra/database/SpeciesRepository.ts
Issue #157  The GET /species need to return desc
> feat: get species need to return description

- server/infra/database/TreeRepository.ts
> fix: wrong token_id response

- server/infra/database/WalletsRepository.ts
- server/models/Wallets.ts
- server/routers/walletsRouter.ts
Added GET wallets/ route with reference to #146.
Added name attribute as a filter.
> feat: Added GET /wallets route

- package-lock.json
- package.json
- server/routers/countriesRouter.ts
- tsconfig.json
- typings-custom/express-lru.d.ts
> feat: express-lru cache for countries/leaderboard

- __tests__/e2e/tokens.spec.ts
- server/infra/database/TokensRepository.ts
> feat: get token by id to return 404 for invalid id

- server/infra/database/TransactionRepository.ts
- server/interfaces/Transaction.ts
> feat: Added source_wallet_logo_url in /transactions

- server/infra/database/PlanterRepository.ts
> feat: add country_id and country_name to /trees/featured #166

- server/infra/database/PlanterRepository.ts
> feat: add created_at field at GET /planters/{id} and GET /planters

- __tests__/e2e/organizations.spec.ts
- server/infra/database/OrganizationRepository.ts
- server/models/Organization.ts
- server/routers/organizationsRouter.ts
> feat: get organization by map name

- server/infra/database/TreeRepository.ts
> fix /trees result id as the tree_id

- server/infra/database/WalletsRepository.ts
> Removed salt and password from GET /wallets route

- server/infra/database/OrganizationRepository.ts
> fixed organization query for planter_id

- server/infra/database/TreeRepository.ts
> Added species_desc to GET /trees/{id}

- server/infra/database/TreeRepository.ts
> typo - count sql statement variable unused

- server/infra/database/TokensRepository.ts
- server/models/Tokens.ts
- server/routers/tokensRouter.ts
> Added count query for GET /tokens.

- server/infra/database/TreeRepository.ts
fix issue #166. Honestly, I think my previous code added the country_id and country_name to trees/featured, not sure why it was not working in the dev. Let me know if there is an issue.
> feat: add country_id and country_name to trees/featured #166

- server/infra/database/OrganizationRepository.ts
> Added country_id and continent_id to /org/{id}

- server/infra/database/PlanterRepository.ts
- server/models/Planter.ts
- server/routers/plantersRouter.ts
> fix: fixes total value of GET /planters

- __tests__/e2e/planters.spec.ts
- server/infra/database/OrganizationRepository.ts
- server/infra/database/PlanterRepository.ts
- server/infra/database/WalletsRepository.ts
- server/infra/database/patch.ts
> feat: can patch planter single

- server/infra/database/TreeRepository.ts
> fix: Added country & species info for trees?org

- server/infra/database/CountryRepository.ts
> feat: made sql query for getting country leaderboard stats fast

- server/routers/countriesRouter.ts
> fix: Added new GET /leaderboard route

- server/infra/database/PlanterRepository.ts
> Added country & continent for planter filter

- server/infra/database/TreeRepository.ts
- server/models/Tree.ts
- server/routers/treesRouter.ts
- Added country & continent for planter filter
- Added planter location based on trees
- fix: query to remove duplicate records
- feat: add filter by wallet for trees
> trees filter by wallet

- server/infra/database/OrganizationRepository.ts
> Added country, continent, id to GET/org/id

- server/infra/database/OrganizationRepository.ts
- server/infra/database/PlanterRepository.ts
> fix: wrong id by location

- .eslintrc.js
- server/routers/organizationsRouter.ts
> fix: get org by mapname

- server/infra/database/CountryRepository.ts
- fix: org id return null
- feat: new way to get country leader board
> new country

- server/infra/database/SpeciesRepository.ts
- server/infra/database/TreeRepository.ts
> feat: take planting_ogranzation_id in consideration

- .github/workflows/pull-request-ci.yml
> feat: add repository unit tests to CI

- server/routers/countriesRouter.ts
- server/routers/growerAccountsRouter.ts
- server/routers/organizationsRouter.ts
- server/routers/organizationsRouterV2.ts
- server/routers/plantersRouter.ts
- server/routers/rawCapturesRouter.ts
- server/routers/speciesRouter.ts
- server/routers/tokensRouter.ts
- server/routers/transactionsRouter.ts
- server/routers/treesRouter.ts
- server/routers/treesRouterV2.ts
- server/routers/walletsRouter.ts
I haven't changed limit in capture routes which is 20000 to 100
> fix: chaged the records limit to 100

- server/routers/treesRouter.ts
- server/routers/treesRouterV2.ts
by default tree order  by time_created
> fix: #291 tress order by default time_created

- server/routers/countriesRouter.ts
- server/routers/growerAccountsRouter.ts
- server/routers/organizationsRouter.ts
- server/routers/organizationsRouterV2.ts
- server/routers/plantersRouter.ts
- server/routers/rawCapturesRouter.ts
- server/routers/speciesRouter.ts
- server/routers/tokensRouter.ts
- server/routers/transactionsRouter.ts
- server/routers/treesRouter.ts
- server/routers/treesRouterV2.ts
- server/routers/walletsRouter.ts
Reverts Greenstand/treetracker-query-api#292
> Revert "fix: chaged the records limit to 100"

- server/infra/database/GrowerAccountRepository.ts
- server/models/GrowerAccount.ts
- server/routers/growerAccountsRouter.ts
> #299 - Implement API: GET Wallets related to growers

- server/infra/database/TreeRepository.ts
- server/routers/treesRouter.ts
> fix: wrong tree count

- server/infra/database/PlanterRepository.ts
> fix: wrong planter count

- server/infra/database/TokensRepository.ts
- server/infra/database/TreeRepository.ts
- server/infra/database/TreeRepositoryV2.ts
- server/infra/database/WalletsRepository.ts
Reverts Greenstand/treetracker-query-api#309
> Revert "fix: uuid capital problem"

- server/infra/database/TokensRepository.ts
> fix: shows only acitve trees for GET /tokens

- server/infra/database/OrganizationRepository.ts
- server/infra/database/OrganizationRepositoryV2.ts
- server/models/Organization.ts
- server/models/OrganizationV2.ts
- server/routers/organizationsRouterV2.ts
> Filter by grower_id

- server/infra/database/SpeciesRepository.ts
- server/infra/database/SpeciesRepositoryV2.ts
- server/models/Organization.ts
- server/models/OrganizationV2.ts
- server/models/Species.ts
- server/models/SpeciesV2.ts
- server/routers/organizationsRouter.ts
- server/routers/organizationsRouterV2.ts
- server/routers/speciesRouter.ts
- server/routers/speciesRouterV2.ts
fixes #345
Adds a count by filter functionality for Organization and Species
> Organization and Species total counter

- server/routers/treesRouter.ts
for the issue: [https://github.com/Greenstand/treetracker-query-api/issues/234](https://github.com/Greenstand/treetracker-query-api/issues/234)
Check if `active===false` at the handler and throw 404.
> fix: do not display inactive trees, and throw 404 error

- server/infra/database/SpeciesRepositoryV2.ts
- server/interfaces/SpeciesFilter.ts
- server/models/SpeciesV2.ts
- server/routers/speciesRouterV2.ts
Species V2 doesnot use herbarium.species and follows legacy version. This fixes that
> fix: species v2

- server/infra/database/BoundsRepository.ts
- server/interfaces/GrowerAccountFilter.ts
- server/models/Bounds.ts
Fixes error #362 
Some other things:
- Shouldn't we make it either `organisation_id` or `organization_id`? There are some instances of both in the server
> fix: added new type allowance for organization_id

- docs/api/spec/query-api.yaml
Comment: I update the stakeholder definition for the v2 web map. 
Issue: This is related to #1769
> Update yaml file

- .github/workflows/pull-request-ci.yml
- package-lock.json
[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'
This branch updates the version of Node using by GitHub Actions to v20. Node v16 was being used previously, which has been [deprecated by GitHub Actions](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/), and was causing the CI run to fail/abort before tests were run.
Fixes [#373](https://github.com/Greenstand/treetracker-query-api/issues/373)
[comment]: # 'Please delete options that are not relevant.'
> GitHub Actions Reconfig for Test Run

- .github/workflows/treetracker-query-api-build-deploy-dev.yml
fixes #381 
(the workflow error that commit https://github.com/Greenstand/treetracker-query-api/commit/168d9e1f6d169c5d7471c81021c50a689268933d had)
> fix: update Node.js version to 20.8.1 for semantic-release
